### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by johnnymetz** [FranckFreiburger/vue-pdf#100]
The demo is showing a blank white page: https://jsfiddle.net/fossfiddler/5k4ptmqg/145/

Not sure if this is happening just for me but it's a pretty big deal as it restrains new users from getting started with this great library.

**Comment by divdax** [comment]
Same here

**Comment by kashiif** [comment]
Can confirm the issue is in both Chrome 67 and Firefox 61

**Comment by johnnymetz** [comment]
Correct, I have tried both browsers with the corresponding versions.

**Comment by FranckFreiburger** [comment]
Demo is broken, I need to find something better than jsfiddle.net

**Comment by FranckFreiburger** [comment]
see #78

**Comment by the94air** [comment]
@FranckFreiburger You can try https://codesandbox.io , They even have a (full page) preview mode by visiting: https://[Your sandbox ID].codesandbox.io

**Comment by FranckFreiburger** [comment]
@the94air, thanks for the trick, but I am unable to setup a demo on codesandbox.io, because webpack `worker-loader` is not working -or- because pdf.js is not able to locate its fake worker on codesandbox.io (`"Error: No "GlobalWorkerOptions.workerSrc" specified."`)

**Comment by the94air** [comment]
I tried to make a demo order by the readme example yesterday and got the same error. The issue happens when you try to use the package into vue and it shows you the "_worker blaa blaa...._" error. I also found that the pdf you are using for the demo is not accessible normally via browser and it shows an error from "cloudfront". First you will need a working pdf url (and [Cross-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) shared).
Due to the limitations of all the sandboxes websites, you will need at least a static hosting. You can try netlify.com. They will be happy to give a free account to an open source project https://www.netlify.com/open-source/. Good luck :+1:
